apiVersion: v1
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeU1URXdOVEl3TWpFMU5Wb1hEVE15TVRFd01qSXdNakUxTlZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTWhtCjBQWjRzUTBjTHFLVlFkajYyZ3pLbHNPbjBlamJYTHFXSm9xYTJyUTkxUGRiMlVRMHdJaVc4Ri85QkxPcTEzZzkKRVVLeDhsMVlWTDBYWG1vbEFPeDd5cSs1OXEyNk91ZytmTUlocldMNlNFY1RFQ3hBOGhxVExpMWtrWi9jSVpYbgpWdWQzaHlFQkRiRlJYMVZtaytHcHQxcENGSDJVWVRJbmlNL2ROVnV0YjM2OGN6WlJTbjY2MDVEM3B1d0tIdGk0CjEvV2hsa2FMUC9sQXN5SXJYSDhaWVdKNlJOTDdSb2pSMjBvRDBmMHVHQ3ZDM3JSTlNHNDI5UG9ONHZPSm5mQ3cKVFQ1YytoclZhTHdPalRjbm9lVnY4ODM2c2hOVkdzRjB0d1VLNjByeFB1dDlGUVFKWmZQNndqcjZBR2k2bk1rLwp6aGlmM2p3T0lCVW1PcXV2ZktrQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZLUjBsQkdnNTRoSFg3UUdGS3pzaUNSNlhxbm1NQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQmlseG1LMWVDdlB4ckpDMVhXMAo0NUZiUWZDQnQxOWtCSjlmZ2kvdzdLak1jT0ZKcFN1eTZDMjNzMFZ3aTAzcjB1WkRaQjVVUFhsSmpxeWFpdTQyCjg5M1IrWVNveTBGekRYVkFpS2FlTitEbXNMbm82SVN5dE1Vc010YWQ2NUE4STQ3d2x0ZHRzK0pkWm5ub1M2bTMKbTlqcExMM2hGaDd1Qmx2WkhaRm9pNU9rTGduYWhxYkJTSFhrYklRK3QrcEZ3QkN3V2dKSEQxVHAzZkE3UUlaRQp0MnJXMUYzY0VJUUdXWmlCY05BbnhleVYyQWRnNmhnNmJlSjQzcytjamZoTmdmMU9pWUN0M2pHbU9rcmxMdXBkCnVMTE1ucHo3SlVCM29KZC9GRUpuQW1Wd1VWM3hOSjltaE4ybTBTdVdPSkY2QkJNNGZRaGdyZHYwcmdVNkRSbHkKTk40PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://09F9C6288361DDF3DE41C15C3419E35F.gr7.eu-west-2.eks.amazonaws.com
  name: arn:aws:eks:eu-west-2:386499475784:cluster/eks-cluster-with-new-vpc
contexts:
- context:
    cluster: arn:aws:eks:eu-west-2:386499475784:cluster/eks-cluster-with-new-vpc
    user: arn:aws:eks:eu-west-2:386499475784:cluster/eks-cluster-with-new-vpc
  name: arn:aws:eks:eu-west-2:386499475784:cluster/eks-cluster-with-new-vpc
current-context: arn:aws:eks:eu-west-2:386499475784:cluster/eks-cluster-with-new-vpc
kind: Config
preferences: {}
users:
- name: arn:aws:eks:eu-west-2:386499475784:cluster/eks-cluster-with-new-vpc
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - eu-west-2
      - eks
      - get-token
      - --cluster-name
      - eks-cluster-with-new-vpc
      command: aws

